# name: Push Workflow

# on: [push,pull_request]

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - name : Print message
#         run : echo "Hello, Github Action"
#   say-bye:
#     needs : job1
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print message
#         run : echo "bye from 2nd job "

name : Uses Action
on : push
jobs:
  development:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code // clone a repo
        uses : actions/checkout@v4
      
      - name : setup node
        uses : actions/setup-node@v4

      - name : Download dependency
        run : npm i 

      - name : Run tests
        run : npm run test

      - name : list file
        run : ls 
  deploy-app:
    needs : development
    runs-on: ubuntu-latest
    steps:
      - name : deply 
        run : echo "deploy success"